### ISSUE TITLE
Edit watch and to watch list

### ISSUE THREAD

**Issue by Caruki** [Caruki/show-cased#8]
## User story
**As a user**
I want to be able to interact with the site
so I can add and edit to watch lists

## Info / Notes / Clarification
- list information for new user comes from alert after sign up
- list information for user edit comes from user interaction with buttons (interaction with result from tmdb api)

## Requirements (from previous issues)
- [x] user database (issue #6 )
- [x] user context to access user information everywhere (issue #41 )

- [x] edit lists (issue #3 and #7 )

## To do
- [x] function to process user input
- [x] ability to copy/paste selected item into user db lists
- [x] function to read lists from user db and get data from api based on it 
- [x] show lists in UI

## Check
- [x] check before merge: correct user db entries

##  Resources / Images
- how to get information from api and write into mongodb

## Criteria
- [x] able to add items to watch and watched list
- [x] UI feedback 
- [x] UI to show lists
